"""pedido con marca modelo mercado y catalogo de piezas

Revision ID: 53dce9e19eb6
Revises: 6246ff048835
Create Date: 2026-09-30 13:03:31.198410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dce9e19eb6'
down_revision: Union[str, Sequence[str], None] = '6246ff048835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CATALOGO_PIEZAS',
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.Unicode(length=150), nullable=False),
    sa.Column('simetrica', sa.String(length=3), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo', name=op.f('PK_CATALOGO_PIEZAS')),
    schema='PLN'
    )
    # 1. columnas nuevas, primero opcionales para poder llenarlas si ya hay pedidos
    op.add_column('PEDIDOS', sa.Column('marca', sa.Unicode(length=80), nullable=True), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('version_vehiculo', sa.Unicode(length=120), nullable=True), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('plataforma', sa.Unicode(length=80), nullable=True), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('mercado', sa.Unicode(length=40), nullable=True), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('tipo_vidrio', sa.String(length=10), nullable=False,
                                       server_default='original'), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('info_en_drive', sa.Boolean(), nullable=True), schema='PLN')
    op.alter_column('PEDIDOS', 'vin', existing_type=sa.VARCHAR(length=17), type_=sa.UnicodeText(),
                    nullable=True, schema='PLN')

    # 2. rescatar lo que ya existia antes de borrar las columnas viejas
    op.execute("""
        UPDATE PLN.PEDIDOS SET
            marca = vehiculo,
            modelo = COALESCE(modelo, N''),
            mercado = COALESCE(cliente, N'Sin definir'),
            vin = COALESCE(vin, N'')
    """)

    # 3. ahora si, obligatorias
    op.alter_column('PEDIDOS', 'marca', existing_type=sa.Unicode(length=80), nullable=False, schema='PLN')
    op.alter_column('PEDIDOS', 'mercado', existing_type=sa.Unicode(length=40), nullable=False, schema='PLN')
    op.alter_column('PEDIDOS', 'modelo', existing_type=sa.Unicode(length=120), nullable=False, schema='PLN')
    op.alter_column('PEDIDOS', 'vin', existing_type=sa.UnicodeText(), nullable=False, schema='PLN')
    op.drop_column('PEDIDOS', 'cliente', schema='PLN')
    op.drop_column('PEDIDOS', 'vehiculo', schema='PLN')
    op.add_column('PEDIDO_PIEZAS', sa.Column('codigo', sa.String(length=3), nullable=True), schema='PLN')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PEDIDO_PIEZAS', 'codigo', schema='PLN')
    op.add_column('PEDIDOS', sa.Column('vehiculo', sa.NVARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('cliente', sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True), schema='PLN')
    op.alter_column('PEDIDOS', 'vin',
               existing_type=sa.UnicodeText(),
               type_=sa.VARCHAR(length=17, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               schema='PLN')
    op.alter_column('PEDIDOS', 'modelo',
               existing_type=sa.NVARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               schema='PLN')
    op.drop_column('PEDIDOS', 'info_en_drive', schema='PLN')
    op.drop_column('PEDIDOS', 'tipo_vidrio', schema='PLN', mssql_drop_default=True)  # SQL Server: primero quita el default
    op.drop_column('PEDIDOS', 'mercado', schema='PLN')
    op.drop_column('PEDIDOS', 'plataforma', schema='PLN')
    op.drop_column('PEDIDOS', 'version_vehiculo', schema='PLN')
    op.drop_column('PEDIDOS', 'marca', schema='PLN')
    op.drop_table('CATALOGO_PIEZAS', schema='PLN')
    # ### end Alembic commands ###
