"""alertas por correo de cada usuario

Revision ID: 8719ed779b5f
Revises: 53dce9e19eb6
Create Date: 2026-10-01 09:40:05.061613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8719ed779b5f'
down_revision: Union[str, Sequence[str], None] = '53dce9e19eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USUARIOS', sa.Column('alertas_correo', sa.String(length=500), nullable=True), schema='PLN')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USUARIOS', 'alertas_correo', schema='PLN')
    # ### end Alembic commands ###
