"""ingreso del pedido codigo de vehiculo numero y aprobacion

Revision ID: 105d4ae58847
Revises: 8719ed779b5f
Create Date: 2026-10-01 14:45:53.612083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105d4ae58847'
down_revision: Union[str, Sequence[str], None] = '8719ed779b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ADJUNTOS', sa.Column('categoria', sa.String(length=20), server_default='general', nullable=False), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('codigo_vehiculo', sa.Unicode(length=80), nullable=True), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('codigo_vehiculo_en', sa.DateTime(), nullable=True), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('codigo_vehiculo_por_id', sa.Integer(), nullable=True), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('numero_pedido', sa.Unicode(length=60), nullable=True), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('numero_pedido_en', sa.DateTime(), nullable=True), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('numero_pedido_por_id', sa.Integer(), nullable=True), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('aprobado_en', sa.DateTime(), nullable=True), schema='PLN')
    op.add_column('PEDIDOS', sa.Column('aprobado_por_id', sa.Integer(), nullable=True), schema='PLN')
    op.create_foreign_key(op.f('FK_PEDIDOS_codigo_vehiculo_por_id_USUARIOS'), 'PEDIDOS', 'USUARIOS', ['codigo_vehiculo_por_id'], ['id'], source_schema='PLN', referent_schema='PLN')
    op.create_foreign_key(op.f('FK_PEDIDOS_aprobado_por_id_USUARIOS'), 'PEDIDOS', 'USUARIOS', ['aprobado_por_id'], ['id'], source_schema='PLN', referent_schema='PLN')
    op.create_foreign_key(op.f('FK_PEDIDOS_numero_pedido_por_id_USUARIOS'), 'PEDIDOS', 'USUARIOS', ['numero_pedido_por_id'], ['id'], source_schema='PLN', referent_schema='PLN')

    # --- datos ---
    # permiso nuevo para tecnica y admin: crear codigo de vehiculo y aprobar el ingreso
    op.execute("""
        INSERT INTO PLN.PERMISOS (codigo, descripcion)
        SELECT 'ingreso.gestionar', N'Marcar el código de vehículo creado y aprobar el ingreso del pedido'
        WHERE NOT EXISTS (SELECT 1 FROM PLN.PERMISOS WHERE codigo = 'ingreso.gestionar')
    """)
    op.execute("""
        INSERT INTO PLN.ROLES_PERMISOS (rol_id, permiso_id)
        SELECT r.id, p.id FROM PLN.ROLES r CROSS JOIN PLN.PERMISOS p
        WHERE r.codigo IN ('tecnico', 'admin') AND p.codigo = 'ingreso.gestionar'
          AND NOT EXISTS (SELECT 1 FROM PLN.ROLES_PERMISOS x WHERE x.rol_id = r.id AND x.permiso_id = p.id)
    """)
    # las 3 alertas nuevas tambien mandan correo por defecto
    op.execute("""
        UPDATE PLN.CONFIGURACION
        SET valor = valor + ',ingreso.codigo_creado,ingreso.pedido_ingresado,ingreso.aprobado'
        WHERE clave = 'correo.eventos' AND valor NOT LIKE '%ingreso.%'
    """)
    # los pedidos que ya salieron de la primera columna se dan por aprobados (eran de antes de esta regla)
    op.execute("""
        UPDATE p SET aprobado_en = SYSUTCDATETIME()
        FROM PLN.PEDIDOS p
        WHERE p.aprobado_en IS NULL
          AND p.columna_id NOT IN (SELECT id FROM PLN.COLUMNAS WHERE es_inicial = 1)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK_PEDIDOS_numero_pedido_por_id_USUARIOS'), 'PEDIDOS', schema='PLN', type_='foreignkey')
    op.drop_constraint(op.f('FK_PEDIDOS_aprobado_por_id_USUARIOS'), 'PEDIDOS', schema='PLN', type_='foreignkey')
    op.drop_constraint(op.f('FK_PEDIDOS_codigo_vehiculo_por_id_USUARIOS'), 'PEDIDOS', schema='PLN', type_='foreignkey')
    op.drop_column('PEDIDOS', 'aprobado_por_id', schema='PLN')
    op.drop_column('PEDIDOS', 'aprobado_en', schema='PLN')
    op.drop_column('PEDIDOS', 'numero_pedido_por_id', schema='PLN')
    op.drop_column('PEDIDOS', 'numero_pedido_en', schema='PLN')
    op.drop_column('PEDIDOS', 'numero_pedido', schema='PLN')
    op.drop_column('PEDIDOS', 'codigo_vehiculo_por_id', schema='PLN')
    op.drop_column('PEDIDOS', 'codigo_vehiculo_en', schema='PLN')
    op.drop_column('PEDIDOS', 'codigo_vehiculo', schema='PLN')
    op.drop_column('ADJUNTOS', 'categoria', schema='PLN', mssql_drop_default=True)
    # ### end Alembic commands ###
