"""esquema inicial del planner

Revision ID: e8688d30c827
Revises: 
Create Date: 2026-09-28 10:19:47.420725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8688d30c827'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # consecutivo de pedidos (PED-2026-0001). Autogenerate no detecta secuencias, va a mano
    op.execute(sa.schema.CreateSequence(sa.Sequence('SEQ_PEDIDOS', start=1, schema='PLN')))
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('COLUMNAS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Unicode(length=60), nullable=False),
    sa.Column('descripcion', sa.Unicode(length=200), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('icono', sa.String(length=30), nullable=False),
    sa.Column('es_inicial', sa.Boolean(), nullable=False),
    sa.Column('es_final', sa.Boolean(), nullable=False),
    sa.Column('limite_wip', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_COLUMNAS')),
    schema='PLN'
    )
    op.create_table('CONFIGURACION',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.UnicodeText(), nullable=False),
    sa.Column('descripcion', sa.Unicode(length=250), nullable=True),
    sa.PrimaryKeyConstraint('clave', name=op.f('PK_CONFIGURACION')),
    schema='PLN'
    )
    op.create_table('ETIQUETAS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Unicode(length=40), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_ETIQUETAS')),
    sa.UniqueConstraint('nombre', name=op.f('UQ_ETIQUETAS_nombre')),
    schema='PLN'
    )
    op.create_table('PERMISOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.Unicode(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_PERMISOS')),
    sa.UniqueConstraint('codigo', name=op.f('UQ_PERMISOS_codigo')),
    schema='PLN'
    )
    op.create_table('ROLES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.Unicode(length=60), nullable=False),
    sa.Column('descripcion', sa.Unicode(length=200), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_ROLES')),
    sa.UniqueConstraint('codigo', name=op.f('UQ_ROLES_codigo')),
    schema='PLN'
    )
    op.create_table('ROLES_PERMISOS',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['PLN.PERMISOS.id'], name=op.f('FK_ROLES_PERMISOS_permiso_id_PERMISOS'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['PLN.ROLES.id'], name=op.f('FK_ROLES_PERMISOS_rol_id_ROLES'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id', name=op.f('PK_ROLES_PERMISOS')),
    schema='PLN'
    )
    op.create_table('USUARIOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.Unicode(length=120), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('personaje', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('debe_cambiar_password', sa.Boolean(), nullable=False),
    sa.Column('version_sesion', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('recibir_correos', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['PLN.ROLES.id'], name=op.f('FK_USUARIOS_rol_id_ROLES')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_USUARIOS')),
    sa.UniqueConstraint('usuario', name=op.f('UQ_USUARIOS_usuario')),
    schema='PLN'
    )
    op.create_table('PEDIDOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('vehiculo', sa.Unicode(length=120), nullable=False),
    sa.Column('modelo', sa.Unicode(length=120), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('cliente', sa.Unicode(length=150), nullable=True),
    sa.Column('descripcion', sa.UnicodeText(), nullable=True),
    sa.Column('prioridad', sa.String(length=10), nullable=False),
    sa.Column('fecha_requerida', sa.Date(), nullable=True),
    sa.Column('columna_id', sa.Integer(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('completado_en', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('datos_extra', sa.UnicodeText(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['columna_id'], ['PLN.COLUMNAS.id'], name=op.f('FK_PEDIDOS_columna_id_COLUMNAS')),
    sa.ForeignKeyConstraint(['creado_por_id'], ['PLN.USUARIOS.id'], name=op.f('FK_PEDIDOS_creado_por_id_USUARIOS')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_PEDIDOS')),
    sa.UniqueConstraint('codigo', name=op.f('UQ_PEDIDOS_codigo')),
    schema='PLN'
    )
    op.create_index('IX_PEDIDOS_columna_posicion', 'PEDIDOS', ['columna_id', 'posicion'], unique=False, schema='PLN')
    op.create_table('CHECKLIST',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Unicode(length=300), nullable=False),
    sa.Column('hecho', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('hecho_por_id', sa.Integer(), nullable=True),
    sa.Column('hecho_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hecho_por_id'], ['PLN.USUARIOS.id'], name=op.f('FK_CHECKLIST_hecho_por_id_USUARIOS')),
    sa.ForeignKeyConstraint(['pedido_id'], ['PLN.PEDIDOS.id'], name=op.f('FK_CHECKLIST_pedido_id_PEDIDOS'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_CHECKLIST')),
    schema='PLN'
    )
    op.create_index(op.f('IX_CHECKLIST_pedido_id'), 'CHECKLIST', ['pedido_id'], unique=False, schema='PLN')
    op.create_table('COLA_CORREOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('para', sa.String(length=150), nullable=False),
    sa.Column('asunto', sa.Unicode(length=250), nullable=False),
    sa.Column('html', sa.UnicodeText(), nullable=False),
    sa.Column('evento', sa.String(length=40), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('ultimo_error', sa.Unicode(length=1000), nullable=True),
    sa.Column('proximo_intento_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['PLN.PEDIDOS.id'], name=op.f('FK_COLA_CORREOS_pedido_id_PEDIDOS'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_COLA_CORREOS')),
    schema='PLN'
    )
    op.create_index('IX_COLA_CORREOS_estado_proximo', 'COLA_CORREOS', ['estado', 'proximo_intento_en'], unique=False, schema='PLN')
    op.create_table('HISTORIAL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=40), nullable=False),
    sa.Column('detalle', sa.UnicodeText(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['PLN.PEDIDOS.id'], name=op.f('FK_HISTORIAL_pedido_id_PEDIDOS'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['PLN.USUARIOS.id'], name=op.f('FK_HISTORIAL_usuario_id_USUARIOS')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_HISTORIAL')),
    schema='PLN'
    )
    op.create_index(op.f('IX_HISTORIAL_pedido_id'), 'HISTORIAL', ['pedido_id'], unique=False, schema='PLN')
    op.create_table('MENSAJES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.UnicodeText(), nullable=False),
    sa.Column('respuesta_a_id', sa.Integer(), nullable=True),
    sa.Column('editado_en', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['PLN.USUARIOS.id'], name=op.f('FK_MENSAJES_autor_id_USUARIOS')),
    sa.ForeignKeyConstraint(['pedido_id'], ['PLN.PEDIDOS.id'], name=op.f('FK_MENSAJES_pedido_id_PEDIDOS'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respuesta_a_id'], ['PLN.MENSAJES.id'], name=op.f('FK_MENSAJES_respuesta_a_id_MENSAJES')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_MENSAJES')),
    schema='PLN'
    )
    op.create_index(op.f('IX_MENSAJES_pedido_id'), 'MENSAJES', ['pedido_id'], unique=False, schema='PLN')
    op.create_table('NOTIFICACIONES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.Unicode(length=200), nullable=False),
    sa.Column('cuerpo', sa.Unicode(length=500), nullable=True),
    sa.Column('leida_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['PLN.PEDIDOS.id'], name=op.f('FK_NOTIFICACIONES_pedido_id_PEDIDOS'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['PLN.USUARIOS.id'], name=op.f('FK_NOTIFICACIONES_usuario_id_USUARIOS')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_NOTIFICACIONES')),
    schema='PLN'
    )
    op.create_index('IX_NOTIFICACIONES_usuario_leida', 'NOTIFICACIONES', ['usuario_id', 'leida_en'], unique=False, schema='PLN')
    op.create_table('PEDIDO_ETIQUETAS',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['PLN.ETIQUETAS.id'], name=op.f('FK_PEDIDO_ETIQUETAS_etiqueta_id_ETIQUETAS'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['PLN.PEDIDOS.id'], name=op.f('FK_PEDIDO_ETIQUETAS_pedido_id_PEDIDOS'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pedido_id', 'etiqueta_id', name=op.f('PK_PEDIDO_ETIQUETAS')),
    schema='PLN'
    )
    op.create_table('PEDIDO_MIEMBROS',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['PLN.PEDIDOS.id'], name=op.f('FK_PEDIDO_MIEMBROS_pedido_id_PEDIDOS'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['PLN.USUARIOS.id'], name=op.f('FK_PEDIDO_MIEMBROS_usuario_id_USUARIOS')),
    sa.PrimaryKeyConstraint('pedido_id', 'usuario_id', name=op.f('PK_PEDIDO_MIEMBROS')),
    schema='PLN'
    )
    op.create_table('PEDIDO_PIEZAS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Unicode(length=150), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Unicode(length=500), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['PLN.PEDIDOS.id'], name=op.f('FK_PEDIDO_PIEZAS_pedido_id_PEDIDOS'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_PEDIDO_PIEZAS')),
    schema='PLN'
    )
    op.create_index(op.f('IX_PEDIDO_PIEZAS_pedido_id'), 'PEDIDO_PIEZAS', ['pedido_id'], unique=False, schema='PLN')
    op.create_table('ADJUNTOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('mensaje_id', sa.Integer(), nullable=True),
    sa.Column('nombre_original', sa.Unicode(length=255), nullable=False),
    sa.Column('blob_nombre', sa.Unicode(length=400), nullable=False),
    sa.Column('tipo_mime', sa.String(length=120), nullable=False),
    sa.Column('tamano_bytes', sa.BigInteger(), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['mensaje_id'], ['PLN.MENSAJES.id'], name=op.f('FK_ADJUNTOS_mensaje_id_MENSAJES')),
    sa.ForeignKeyConstraint(['pedido_id'], ['PLN.PEDIDOS.id'], name=op.f('FK_ADJUNTOS_pedido_id_PEDIDOS'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subido_por_id'], ['PLN.USUARIOS.id'], name=op.f('FK_ADJUNTOS_subido_por_id_USUARIOS')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_ADJUNTOS')),
    sa.UniqueConstraint('blob_nombre', name=op.f('UQ_ADJUNTOS_blob_nombre')),
    schema='PLN'
    )
    op.create_index(op.f('IX_ADJUNTOS_pedido_id'), 'ADJUNTOS', ['pedido_id'], unique=False, schema='PLN')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('IX_ADJUNTOS_pedido_id'), table_name='ADJUNTOS', schema='PLN')
    op.drop_table('ADJUNTOS', schema='PLN')
    op.drop_index(op.f('IX_PEDIDO_PIEZAS_pedido_id'), table_name='PEDIDO_PIEZAS', schema='PLN')
    op.drop_table('PEDIDO_PIEZAS', schema='PLN')
    op.drop_table('PEDIDO_MIEMBROS', schema='PLN')
    op.drop_table('PEDIDO_ETIQUETAS', schema='PLN')
    op.drop_index('IX_NOTIFICACIONES_usuario_leida', table_name='NOTIFICACIONES', schema='PLN')
    op.drop_table('NOTIFICACIONES', schema='PLN')
    op.drop_index(op.f('IX_MENSAJES_pedido_id'), table_name='MENSAJES', schema='PLN')
    op.drop_table('MENSAJES', schema='PLN')
    op.drop_index(op.f('IX_HISTORIAL_pedido_id'), table_name='HISTORIAL', schema='PLN')
    op.drop_table('HISTORIAL', schema='PLN')
    op.drop_index('IX_COLA_CORREOS_estado_proximo', table_name='COLA_CORREOS', schema='PLN')
    op.drop_table('COLA_CORREOS', schema='PLN')
    op.drop_index(op.f('IX_CHECKLIST_pedido_id'), table_name='CHECKLIST', schema='PLN')
    op.drop_table('CHECKLIST', schema='PLN')
    op.drop_index('IX_PEDIDOS_columna_posicion', table_name='PEDIDOS', schema='PLN')
    op.drop_table('PEDIDOS', schema='PLN')
    op.drop_table('USUARIOS', schema='PLN')
    op.drop_table('ROLES_PERMISOS', schema='PLN')
    op.drop_table('ROLES', schema='PLN')
    op.drop_table('PERMISOS', schema='PLN')
    op.drop_table('ETIQUETAS', schema='PLN')
    op.drop_table('CONFIGURACION', schema='PLN')
    op.drop_table('COLUMNAS', schema='PLN')
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence('SEQ_PEDIDOS', schema='PLN')))
